from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from skillloop.fs_safety import safe_path_segment
from skillloop.store import SkillLoopStore

OKF_VERSION = "0.1"
CONCEPT_MEMORY_TYPE = "SkillLoop Memory"
CONCEPT_SKILL_TYPE = "SkillLoop Skill"
SUPPORTED_PROPOSAL_KINDS = {"memory", "skill"}


def export_okf_bundle(store: SkillLoopStore, out_dir: str | Path) -> Path:
    approved = [p for p in store.list_proposals(status="approved") if p.kind in SUPPORTED_PROPOSAL_KINDS]
    bundle_root = Path(out_dir).resolve()
    bundle_root.mkdir(parents=True, exist_ok=True)

    concepts_dir = bundle_root / "concepts"
    concepts_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).isoformat()
    entries: list[tuple[str, str, str, str, str]] = []
    written: list[Path] = []

    for proposal in approved:
        proposal_id = safe_path_segment(proposal.id, label="proposal id")
        concept_type = CONCEPT_SKILL_TYPE if proposal.kind == "skill" else CONCEPT_MEMORY_TYPE
        concept_title = proposal.title or f"{proposal.kind}-{proposal_id[:8]}"
        description = proposal.reason or ""

        tags = [proposal.kind, "skillloop-approved"]
        score = _find_evaluation_score(store, proposal.trace_id)
        resource_uri = None
        if proposal.trace_id:
            resource_uri = f"skillloop:trace:{proposal.trace_id}"
            tags.append(f"trace:{proposal.trace_id[:12]}")

        frontmatter_lines = [
            "---",
            f"type: {concept_type}",
            f"title: {concept_title}",
            f"description: {description}",
        ]
        if resource_uri:
            frontmatter_lines.append(f"resource: {resource_uri}")
        frontmatter_lines.append(f"tags: [{', '.join(tags)}]")
        frontmatter_lines.append(f"timestamp: {timestamp}")
        frontmatter_lines.extend([
            f"proposal_id: {proposal_id}",
            f"source_trace_id: {proposal.trace_id}",
            f"proposal_kind: {proposal.kind}",
        ])
        if score is not None:
            frontmatter_lines.append(f"score: {score}")
        frontmatter_lines.append("---")

        frontmatter = "\n".join(frontmatter_lines) + "\n"
        content = f"{frontmatter}\n# {concept_title}\n\n{proposal.content}\n"

        concept_path = concepts_dir / f"{proposal.kind}_{proposal_id}.md"
        concept_path.write_text(content, encoding="utf-8")
        written.append(concept_path)

        relative_href = f"concepts/{proposal.kind}_{proposal_id}.md"
        entries.append((concept_title, relative_href, concept_type, description, proposal.kind, proposal.trace_id))

    _write_index(bundle_root, entries)
    _write_log(bundle_root, entries, timestamp)
    _write_okf_version(bundle_root, timestamp)

    return bundle_root


def _write_index(bundle_root: Path, entries: list[tuple[str, str, str, str, str, str]]) -> None:
    lines = ["# SkillLoop Approved Knowledge Bundle\n"]
    sections: dict[str, list[tuple[str, str, str, str, str, str]]] = {}
    for entry in entries:
        kind = entry[4]
        sections.setdefault(kind, []).append(entry)

    for kind_label in ["skill", "memory"]:
        if kind_label not in sections:
            continue
        display = "Skills" if kind_label == "skill" else "Memories"
        lines.append(f"## {display}\n")
        for title, href, ctype, desc, _, _ in sections[kind_label]:
            lines.append(f"* [{title}]({href}) — {desc} ({ctype})\n")
        lines.append("")

    index_path = bundle_root / "index.md"
    index_path.write_text("\n".join(lines), encoding="utf-8")


def _write_log(
    bundle_root: Path,
    entries: list[tuple[str, str, str, str, str, str]],
    timestamp: str,
) -> None:
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines = ["# Bundle Update Log\n", f"## {date_str}\n"]
    for title, href, ctype, desc, kind, trace_id in entries:
        lines.append(f"* **Creation**: [{title}]({href}) — {ctype} from trace `{trace_id}` — {desc}\n")
    log_path = bundle_root / "log.md"
    log_path.write_text("\n".join(lines), encoding="utf-8")


def _write_okf_version(bundle_root: Path, timestamp: str) -> None:
    readme = bundle_root / "README.md"
    content = (
        f"---\n"
        f"okf_version: \"{OKF_VERSION}\"\n"
        f"type: Bundle README\n"
        f"title: SkillLoop Knowledge Bundle\n"
        f"description: Approved learning artifacts exported from SkillLoop as an OKF v{OKF_VERSION} bundle.\n"
        f"timestamp: {timestamp}\n"
        f"---\n\n"
        f"# SkillLoop Knowledge Bundle\n\n"
        f"This is an [OKF v{OKF_VERSION}](https://github.com/GoogleCloudPlatform/knowledge-catalog/blob/main/okf/SPEC.md) "
        f"knowledge bundle generated by [SkillLoop](https://github.com) — a governed learning layer for AI agents.\n\n"
        f"## Contents\n\n"
        f"* [Concept index](index.md)\n"
        f"* [Update log](log.md)\n"
        f"* [Concepts directory](concepts/)\n"
    )
    readme.write_text(content, encoding="utf-8")


def _find_evaluation_score(store: SkillLoopStore, trace_id: str) -> int | None:
    try:
        for ev in store.list_evaluations():
            if ev.trace_id == trace_id:
                return ev.score
    except Exception:
        pass
    return None
