from __future__ import annotations

from skillloop.interfaces.cli import (
    build_parser,
    cmd_apply,
    cmd_benchmark,
    cmd_controller_history,
    cmd_controller_run,
    cmd_controller_show,
    cmd_distill,
    cmd_doctor,
    cmd_eval,
    cmd_export,
    cmd_ingest,
    cmd_init,
    cmd_loop_run,
    cmd_loop_schedule,
    cmd_loop_status,
    cmd_loop_tick,
    cmd_review_approve,
    cmd_review_list,
    cmd_review_reject,
    cmd_service_install,
    cmd_service_status,
    cmd_service_uninstall,
    cmd_setup,
    cmd_status,
    cmd_traces_list,
    cmd_traces_show,
    cmd_training_config,
    main,
)

__all__ = [
    "build_parser",
    "cmd_apply",
    "cmd_benchmark",
    "cmd_controller_history",
    "cmd_controller_run",
    "cmd_controller_show",
    "cmd_distill",
    "cmd_doctor",
    "cmd_eval",
    "cmd_export",
    "cmd_ingest",
    "cmd_init",
    "cmd_loop_run",
    "cmd_loop_schedule",
    "cmd_loop_status",
    "cmd_loop_tick",
    "cmd_review_approve",
    "cmd_review_list",
    "cmd_review_reject",
    "cmd_service_install",
    "cmd_service_status",
    "cmd_service_uninstall",
    "cmd_setup",
    "cmd_status",
    "cmd_traces_list",
    "cmd_traces_show",
    "cmd_training_config",
    "main",
]


if __name__ == "__main__":
    raise SystemExit(main())
