from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from skillloop.schema import now_iso, sha256_text, stable_json_dumps

SUPPORTED_TRAINING_TARGETS = {"unsloth", "trl", "axolotl"}


@dataclass
class TrainingConfigRequest:
    target: str
    dataset_manifest: str
    base_model: str
    output_dir: str
    config_dir: str | Path
    learning_rate: float = 2e-4
    epochs: int = 1
    per_device_batch_size: int = 1
    gradient_accumulation_steps: int = 4
    max_seq_length: int = 2048
    lora_rank: int = 16
    lora_alpha: int = 16

    def __post_init__(self) -> None:
        if self.target not in SUPPORTED_TRAINING_TARGETS:
            raise ValueError(f"unsupported training target: {self.target}")


def load_manifest(path: str | Path) -> dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _dataset_path(manifest: dict[str, Any], split: str = "train") -> str:
    files = manifest.get("output_files") or {}
    return str(files.get(split) or next(iter(files.values()), ""))


def _common_payload(request: TrainingConfigRequest, manifest: dict[str, Any]) -> dict[str, Any]:
    return {
        "generated_at": now_iso(),
        "target": request.target,
        "base_model": request.base_model,
        "dataset_manifest": str(Path(request.dataset_manifest).resolve()),
        "dataset_manifest_id": manifest.get("id"),
        "dataset_kind": manifest.get("kind"),
        "dataset_records": manifest.get("records"),
        "dataset_estimated_tokens": manifest.get("estimated_tokens"),
        "train_file": _dataset_path(manifest, "train"),
        "output_dir": request.output_dir,
        "hyperparameters": {
            "learning_rate": request.learning_rate,
            "epochs": request.epochs,
            "per_device_batch_size": request.per_device_batch_size,
            "gradient_accumulation_steps": request.gradient_accumulation_steps,
            "max_seq_length": request.max_seq_length,
            "lora_rank": request.lora_rank,
            "lora_alpha": request.lora_alpha,
        },
        "safety": {
            "execution": "config_generation_only",
            "training_auto_run": False,
            "requires_manual_review": True,
        },
    }


def _write_json(path: Path, payload: dict[str, Any]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return path


def _write_text(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


def _yaml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return json.dumps(str(value))


def _write_simple_yaml(path: Path, payload: dict[str, Any]) -> Path:
    lines: list[str] = []
    for key, value in payload.items():
        if isinstance(value, dict):
            lines.append(f"{key}:")
            for child_key, child_value in value.items():
                lines.append(f"  {child_key}: {_yaml_scalar(child_value)}")
        else:
            lines.append(f"{key}: {_yaml_scalar(value)}")
    return _write_text(path, "\n".join(lines) + "\n")


def generate_unsloth_config(
    request: TrainingConfigRequest, manifest: dict[str, Any]
) -> dict[str, Path]:
    payload = _common_payload(request, manifest)
    payload.update(
        {
            "library": "unsloth",
            "script_note": "Review this generated config before manually launching any Unsloth training script.",
        }
    )
    config_dir = Path(request.config_dir).resolve()
    config_path = _write_json(config_dir / "unsloth_config.json", payload)
    script = f"""# Generated by SkillLoop. Review before running. This file does not auto-run training.
from datasets import load_dataset
from trl import SFTTrainer
from unsloth import FastLanguageModel

MODEL_NAME = {request.base_model!r}
TRAIN_FILE = {payload["train_file"]!r}
OUTPUT_DIR = {request.output_dir!r}
MAX_SEQ_LENGTH = {request.max_seq_length}

# Manual training skeleton only. Fill tokenizer formatting/collator choices before running.
model, tokenizer = FastLanguageModel.from_pretrained(model_name=MODEL_NAME, max_seq_length=MAX_SEQ_LENGTH)
dataset = load_dataset("json", data_files=TRAIN_FILE, split="train")
trainer = SFTTrainer(model=model, tokenizer=tokenizer, train_dataset=dataset, max_seq_length=MAX_SEQ_LENGTH)
# trainer.train()
# trainer.save_model(OUTPUT_DIR)
"""
    script_path = _write_text(config_dir / "unsloth_sft_skeleton.py", script)
    return {"config": config_path, "script": script_path}


def generate_trl_config(
    request: TrainingConfigRequest, manifest: dict[str, Any]
) -> dict[str, Path]:
    payload = _common_payload(request, manifest)
    payload.update(
        {
            "library": "trl",
            "trainer": "SFTTrainer",
            "script_note": "Manual TRL SFT config; no execution performed.",
        }
    )
    config_dir = Path(request.config_dir).resolve()
    return {"config": _write_json(config_dir / "trl_sft_config.json", payload)}


def generate_axolotl_config(
    request: TrainingConfigRequest, manifest: dict[str, Any]
) -> dict[str, Path]:
    common = _common_payload(request, manifest)
    hp = common["hyperparameters"]
    payload = {
        "base_model": request.base_model,
        "output_dir": request.output_dir,
        "sequence_len": hp["max_seq_length"],
        "learning_rate": hp["learning_rate"],
        "num_epochs": hp["epochs"],
        "micro_batch_size": hp["per_device_batch_size"],
        "gradient_accumulation_steps": hp["gradient_accumulation_steps"],
        "adapter": "lora",
        "lora_r": hp["lora_rank"],
        "lora_alpha": hp["lora_alpha"],
        "datasets": {"path": common["train_file"], "type": common["dataset_kind"] or "sft"},
        "skillloop": {
            "dataset_manifest": common["dataset_manifest"],
            "dataset_manifest_id": common["dataset_manifest_id"],
            "training_auto_run": False,
        },
    }
    config_dir = Path(request.config_dir).resolve()
    return {"config": _write_simple_yaml(config_dir / "axolotl_config.yml", payload)}


def generate_training_config(request: TrainingConfigRequest) -> dict[str, Any]:
    manifest = load_manifest(request.dataset_manifest)
    if request.target == "unsloth":
        files = generate_unsloth_config(request, manifest)
    elif request.target == "trl":
        files = generate_trl_config(request, manifest)
    elif request.target == "axolotl":
        files = generate_axolotl_config(request, manifest)
    else:  # pragma: no cover - guarded by dataclass
        raise ValueError(f"unsupported training target: {request.target}")
    summary = {
        "target": request.target,
        "dataset_manifest": str(Path(request.dataset_manifest).resolve()),
        "dataset_manifest_id": manifest.get("id"),
        "files": {name: str(path) for name, path in files.items()},
        "execution": "config_generation_only",
        "training_auto_run": False,
    }
    summary["id"] = sha256_text(stable_json_dumps(summary))[:16]
    return summary
